require 'open-uri'

scrapers = [["Bankstown","bankstown_development_applications"],
["Bellingen","bellingen-shire-council-development-applications"],
["Blacktown","blacktown_city_council_development_applications"],
["Blue Mountains","blue-mountains-city-council-development-applicatio"],
["Bundaberg","bundaberg_regional_council_development_application"],
["Charters Towers","charters_towers_regional_council_development_appli"],
["Ballarat (City)","city_of_ballarat_development_applications"],
["Burnside","city_of_burnside_development_applications"],
["Cockburn","city_of_cockburn_development_applications"],
["Geelong (City)","city_of_greater_geelong_development_applications"],
["Kingston","city_of_kingston_development_applications"],
["Marion","city_of_marion_development_applications"],
["Melbourne (City)","city_of_melbourne_planning_applications"],
["Ryde","city_of_ryde_development_applications"],
["Stonnington","city_of_stonnington_development_applications"],
["Sydney","city_of_sydney_development_applications"],
["Unley","city_of_unley_development_applications"],
["Vincent","city_of_vincent_wa_development_applications"],
["Clarence","clarence_city_council_development_applications"],
["Coffs Harbour","coffs_harbour_city_council_development_application"],
["DAPs WA","development_assessment_panel_applications"],
["Gold Coast","gold_coast_city_council_development_applications"],
["Gosford","gosford_nsw_development_applications"],
["Greater Taree","greater_taree_council_development_applications"],
["Hawkesbury","hawkesbury_city_council_development_applications"],
["Hobart","hobart_city_council_development_applications"],
["Knox","knox_regional_council_development_applications"],
["Lane Cove","lane_cove_da_scraper"],
["Leichhardt","leichhardt_municipal_council_development_applicati"],
["Mackay","mackay_city_council_development_applications"],
["Marrickville","marrickville-council-development-applications"],
["Moreton Bay","moreton_bay_regional_council_development_applicati"],
["Mornington Peninsula","mornington_peninsula_shire_-_development_applicati"],
["Mosman","mosman_council_development_applications"],
["Muswellbrook","muswellbrook_shire_council_development_application"],
["Nillumbik","nillumbik_shire_council_development_applications"],
["North Sydney","north_sydney_council_development_applications"],
["Northern Territory","northern_territory_development_applications"],
["NSW DoP","nsw_department_of_planning_major_project_assessmen"],
["NSW JRPP","nsw_joint_regional_planning_panels_development_reg"],
["NSW OLGR","nsw_office_of_liquor_gaming_and_racing_-_liquor_ap"],
["Onkaparinga","onkaparinga_sa_development_applications"],
["Parramatta","parramatta-city-council-development-applications"],
["Penrith","penrith_city_council_development_applications"],
["Perth","perth_development_applications"],
["Pittwater","pittwater_council_development_applications"],
["Port Stephens","port_stephens_development_applications"],
["Randwick","randwick_city_council_development_applications"],
["Rockdale","rockdale_city_council_development_applications_-_r"],
["Scenic Rim","scenic_rim_regional_council_development_applicatio"],
["Yarra Ranges","shire_of_yarra_ranges_planning_applications"],
["Shoalhaven","shoalhaven_council_development_applications"],
["SPEAR Victoria","streamlined_planning_through_electronic_applicatio"],
["Sunshine Coast","sunshine_coast_council_development_applications"],
["Surf Coast Shire","surf_coast_shire_council_development_applications"],
["The Hills","the_hills_shire_council_development_applications"],
["Toowoomba","toowoomba_city_council_planning_and_development_ap"],
["VCGLR","victorian_liquor_licence_applications_1"],
["Waverley","waverley_council_development_applications"],
["Woollahra","woollahra_council_development_applications"],
["Yarra City","yarra_city_development_applications"]]

scrapers.each do |scraper|
  filename = scraper[0].downcase.gsub(' ', '_').gsub('(', '').gsub(')', '') + '.rb'
  File.open(filename, 'w') do |file|
    file.write(open("https://classic.scraperwiki.com/editor/raw/#{scraper[1]}").read)
  end
end
